export const FETCH_PROJECTS = 'FETCH_PROJECTS'
export const FETCH_PROJECTS_SUCCESS = 'FETCH_PROJECTS_SUCCESS'
export const FETCH_PROJECTS_FAIL = 'FETCH_PROJECTS_FAIL'

export const TOGGLE_TASK = 'TOGGLE_TASK'
export const TOGGLE_TASK_SUCCESS = 'TOGGLE_TASK_SUCCESS'
export const TOGGLE_TASK_FAIL = 'TOGGLE_TASK_FAIL'


export const UPDATE_PROJECT = 'UPDATE_PROJECT'
export const UPDATE_PROJECT_SUCCESS = 'UPDATE_PROJECT_SUCCESS'
export const UPDATE_PROJECT_FAIL = 'UPDATE_PROJECT_FAIL'

export const ADD_TASK_TO_PROJECT = 'ADD_TASK_TO_PROJECT'
export const ADD_TASK_TO_PROJECT_SUCCESS = 'ADD_TASK_TO_PROJECT_SUCCESS'
export const ADD_TASK_TO_PROJECT_FAIL = 'ADD_TASK_TO_PROJECT_FAIL'

export const UPDATE_PROJECT_ACTIVITIES = 'UPDATE_PROJECT_ACTIVITIES'

export const ADD_PROJECT = 'ADD_PROJECT'
export const ADD_PROJECT_SUCCESS = 'ADD_PROJECT_SUCCESS'
export const ADD_PROJECT_FAIL = 'ADD_PROJECT_FAIL'
